# Source: akri/templates/debug-echo-configuration.yaml
apiVersion: akri.sh/v0
kind: Configuration
metadata:
  name: akri-debug-echo
spec:
  discoveryHandler: 
    name: debugEcho
    discoveryDetails: |+
      descriptions:
      - foo0
      - foo1
  brokerProperties: {}
  capacity: 2
