apiVersion: apps/v1
kind: DaemonSet
metadata:
  annotations:
    deprecated.daemonset.template.generation: "1"
  creationTimestamp: "2021-06-30T16:11:32Z"
  generation: 1
  name: akri-debug-echo-discovery-daemonset
  namespace: default
  resourceVersion: "6537345"
  selfLink: /apis/apps/v1/namespaces/default/daemonsets/akri-debug-echo-discovery-daemonset
  uid: 5ed9f420-36f5-4b07-92af-e2faf1882c71
spec:
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      name: akri-debug-echo-discovery
  template:
    metadata:
      creationTimestamp: null
      labels:
        name: akri-debug-echo-discovery
    spec:
      containers:
      - env:
        - name: DISCOVERY_HANDLERS_DIRECTORY
          value: /var/lib/akri
        - name: DEBUG_ECHO_INSTANCES_SHARED
          value: "false"
        image: ghcr.io/rodz/wde-discovery-handler:v3.2
        imagePullPolicy: IfNotPresent
        name: akri-debug-echo-discovery
        resources:
          limits:
            cpu: 26m
            memory: 24Mi
          requests:
            cpu: 10m
            memory: 11Mi
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /var/lib/akri
          name: discovery-handlers
          # This is the path krustlet stores data, can be changed by environment variable
        - mountPath: ~/.krustlet/volumes/wasi-debug-echo-default/wde-storage
          name: wde-storage
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
      - hostPath:
          path: /var/lib/akri
          type: ""
        name: discovery-handlers
      - hostPath:
          # This is the path krustlet stores data, can be changed by environment variable
          path: ~/.krustlet/volumes/wasi-debug-echo-default/wde-storage
          type: ""
        name: wde-storage
  updateStrategy:
    rollingUpdate:
      maxUnavailable: 1
    type: RollingUpdate
status:
  currentNumberScheduled: 1
  desiredNumberScheduled: 1
  numberMisscheduled: 0
  numberReady: 0
  numberUnavailable: 1
  observedGeneration: 1
  updatedNumberScheduled: 1
