# This is a Wasi application that is deployed to a Krustlet node.
apiVersion: v1
kind: Pod
metadata:
  name: im-using-debug-echo-devices
spec:
  containers:
    - name: im-using-debug-echo-devices
      image: ghcr.io/rodz/wasi-debug-echo-hello-world:v1
      resources:
        requests:
          "akri.sh/akri-debug-echo-43beb5" : 1
        limits:
          "akri.sh/akri-debug-echo-43beb5" : 1
  nodeSelector:
    kubernetes.io/arch: "wasm32-wasi"
  tolerations:
    - key: "kubernetes.io/arch"
      operator: "Equal"
      value: "wasm32-wasi"
      effect: "NoExecute"
    - key: "node.kubernetes.io/network-unavailable"
      operator: "Exists"
      effect: "NoSchedule"
    - key: "kubernetes.io/arch"
      operator: "Equal"
      value: "wasm32-wasi"
      effect: "NoSchedule"